### ISSUE TITLE
Enable iptables on zgemma 4.4.35 Linux bases stbs

### ISSUE THREAD

**Issue by estimadarocha** [OpenPLi-meta/meta-zgemma#1]
I have tried to copy all the ethernet options on defconfig of octagon sf8008 to the zgemma so i can be able to have iptables on it but i am stucked with kernel panic. 

Any ideas?

The idea behind have iptables on a stb is because some vpn stuff like tailscale zerotier and other advanced mesh vpn systems need to create their own tables to work correctly.

Thanks

**Comment by kueken** [comment]
They are different machines with different libs.
You can't just take over an existing defconfig.
you could test it via the same receivers route from another git.
For example OEA.

**Comment by estimadarocha** [comment]
> They are different machines with different libs. You can't just take over an existing defconfig. you could test it via the same receivers route from another git. For example OEA.

I did... it return a kernel panic with CONFIG_NF_CONNTRACK=m all other options work exactly as it supposed!

look at https://github.com/zgemma-star/meta-zgemma/issues/95

**Comment by kueken** [comment]
I am aware that you did it anyway knowing that it didn't work.
But it doesn't work.
You know it doesn't work
That's not so easy to fix either.
You would have to create a completely new kernel config for this.
There are then certainly costs that hardly any manufacturer can afford.
Whether one can patch the Linux?
I don't think this works that easily either, otherwise it would have happened long ago in the OEA.
